import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-h-fit	m-10">
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/sea-edge/eth-tx-decoder">Ethereum Transaction Decoder!</a>
        </h1>
      </div>
      <form className="flex flex-col h-full">
        <textarea className='
        block
        resize
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-1
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none
        w-3/5
        h-600
        justify-center
        '
          placeholder='Input Raw Transaction! ex.) 0x02fff...'
        // value={input}
        // onChange={e => setInput(e.target.value)}
        />
        <button className="flex justify-center text-3xl font-bold underline">
          Hello world!
        </button>
      </form>



      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
